"use client";

import { useMemo, useState } from "react";
import { Bot, CheckCircle2, Circle, Plus, Trash2 } from "lucide-react";
import { formatDate } from "@/lib/utils";

const CATEGORIES = ["venue", "permits", "staffing", "logistics", "marketing", "other"];

interface ChecklistItem {
  id: string;
  title: string;
  description: string | null;
  isCompleted: boolean;
  dueDate: string;
  category: string | null;
  source: string;
}

export function ChecklistSection({
  eventId,
  initialItems,
}: {
  eventId: string;
  initialItems: ChecklistItem[];
}) {
  const [items, setItems] = useState<ChecklistItem[]>(initialItems);
  const [newTitle, setNewTitle] = useState("");
  const [adding, setAdding] = useState(false);

  async function addItem() {
    if (!newTitle.trim()) return;
    setAdding(true);
    const res = await fetch(`/api/events/${eventId}/checklist`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: newTitle.trim() }),
    });
    const item = await res.json();
    setItems((prev) => [...prev, { ...item, dueDate: "", description: null, category: null }]);
    setNewTitle("");
    setAdding(false);
  }

  async function toggleComplete(id: string, current: boolean) {
    setItems((prev) => prev.map((item) => (item.id === id ? { ...item, isCompleted: !current } : item)));
    await fetch(`/api/events/${eventId}/checklist/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ isCompleted: !current }),
    });
  }

  async function updateItem(id: string, field: string, value: unknown) {
    setItems((prev) => prev.map((item) => (item.id === id ? { ...item, [field]: value } : item)));
    await fetch(`/api/events/${eventId}/checklist/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ [field]: value }),
    });
  }

  async function deleteItem(id: string) {
    setItems((prev) => prev.filter((item) => item.id !== id));
    await fetch(`/api/events/${eventId}/checklist/${id}`, { method: "DELETE" });
  }

  const summary = useMemo(() => {
    const completed = items.filter((item) => item.isCompleted).length;
    const agentGenerated = items.filter((item) => item.source === "agent").length;
    const dueSoon = items.filter((item) => {
      if (!item.dueDate || item.isCompleted) return false;
      const due = new Date(`${item.dueDate}T00:00:00`);
      const diff = due.getTime() - Date.now();
      return diff >= 0 && diff <= 7 * 24 * 60 * 60 * 1000;
    }).length;

    return {
      completed,
      remaining: items.length - completed,
      agentGenerated,
      dueSoon,
      percent: items.length === 0 ? 0 : Math.round((completed / items.length) * 100),
    };
  }, [items]);

  const grouped = useMemo(() => {
    const groups: Record<string, ChecklistItem[]> = {};
    for (const item of items) {
      const key = item.category || "uncategorized";
      if (!groups[key]) groups[key] = [];
      groups[key].push(item);
    }
    return groups;
  }, [items]);

  return (
    <div className="space-y-5">
      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
        <ChecklistSummaryCard label="Completed" value={`${summary.completed}`} hint={`${summary.percent}% of checklist`} />
        <ChecklistSummaryCard label="Remaining" value={`${summary.remaining}`} hint="Still needs execution" />
        <ChecklistSummaryCard label="Due Soon" value={`${summary.dueSoon}`} hint="Within the next 7 days" />
        <ChecklistSummaryCard label="AI Suggested" value={`${summary.agentGenerated}`} hint="Generated by the planning agent" />
      </div>

      {items.length > 0 && (
        <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
          <div className="mb-2 flex items-center justify-between text-xs text-slate-500">
            <span>{summary.completed} of {items.length} complete</span>
            <span>{summary.percent}%</span>
          </div>
          <div className="h-2 overflow-hidden rounded-full bg-slate-200">
            <div
              className="h-full rounded-full bg-[linear-gradient(90deg,#22c55e,#0ea5e9)] transition-all"
              style={{ width: `${summary.percent}%` }}
            />
          </div>
        </div>
      )}

      <div className="rounded-[26px] border border-slate-200 bg-white p-4 shadow-sm">
        <div className="flex flex-col gap-3 sm:flex-row">
          <input
            type="text"
            value={newTitle}
            onChange={(e) => setNewTitle(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && addItem()}
            placeholder="Add the next planning task..."
            className="flex-1 rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-700 outline-none transition-colors placeholder:text-slate-400 focus:border-brand-blue"
          />
          <button
            onClick={addItem}
            disabled={!newTitle.trim() || adding}
            className="inline-flex items-center justify-center gap-2 rounded-2xl bg-slate-900 px-4 py-3 text-sm font-medium text-white transition-colors hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-40"
          >
            <Plus className="h-4 w-4" />
            Add Task
          </button>
        </div>
      </div>

      {items.length === 0 ? (
        <div className="rounded-[24px] border border-dashed border-slate-300 bg-slate-50 px-6 py-12 text-center">
          <p className="text-sm font-medium text-slate-600">No checklist items yet</p>
          <p className="mt-2 text-sm text-slate-500">
            Add the critical tasks that must happen before this event can be locked for execution.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {Object.entries(grouped).map(([group, groupItems]) => (
            <div key={group} className="rounded-[26px] border border-slate-200 bg-white p-4 shadow-sm">
              <div className="mb-4 flex items-center justify-between gap-3">
                <div>
                  <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-400">
                    {group === "uncategorized" ? "General" : group}
                  </p>
                  <p className="mt-1 text-sm text-slate-500">
                    {groupItems.filter((item) => item.isCompleted).length} of {groupItems.length} complete
                  </p>
                </div>
                <span className="rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-xs font-semibold text-slate-600">
                  {groupItems.length} item{groupItems.length === 1 ? "" : "s"}
                </span>
              </div>

              <div className="space-y-3">
                {groupItems.map((item) => (
                  <div
                    key={item.id}
                    className={`rounded-2xl border px-4 py-4 transition-colors ${
                      item.isCompleted
                        ? "border-emerald-200 bg-emerald-50/70"
                        : "border-slate-200 bg-slate-50/70 hover:border-slate-300"
                    }`}
                  >
                    <div className="flex gap-3">
                      <button
                        onClick={() => toggleComplete(item.id, item.isCompleted)}
                        className="mt-0.5 shrink-0 transition-colors"
                      >
                        {item.isCompleted ? (
                          <CheckCircle2 className="h-5 w-5 text-brand-green" />
                        ) : (
                          <Circle className="h-5 w-5 text-slate-300 hover:text-brand-green" />
                        )}
                      </button>

                      <div className="min-w-0 flex-1 space-y-3">
                        <div className="flex flex-wrap items-center gap-2">
                          {item.source === "agent" && (
                            <span className="inline-flex items-center gap-1 rounded-full border border-purple-200 bg-purple-50 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-[0.16em] text-purple-700">
                              <Bot className="h-3 w-3" />
                              AI Suggested
                            </span>
                          )}
                          {item.dueDate && (
                            <span className="rounded-full border border-slate-200 bg-white px-2.5 py-1 text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-500">
                              Due {formatDate(`${item.dueDate}T00:00:00`)}
                            </span>
                          )}
                        </div>

                        <input
                          type="text"
                          value={item.title}
                          onChange={(e) => updateItem(item.id, "title", e.target.value)}
                          className={`w-full border-0 bg-transparent px-0 text-base font-semibold outline-none placeholder:text-slate-300 ${
                            item.isCompleted ? "text-slate-400 line-through" : "text-slate-900"
                          }`}
                        />

                        <div className="grid gap-3 lg:grid-cols-[160px_180px_auto]">
                          <select
                            value={item.category ?? ""}
                            onChange={(e) => updateItem(item.id, "category", e.target.value || null)}
                            className="input-base capitalize"
                          >
                            <option value="">No category</option>
                            {CATEGORIES.map((category) => (
                              <option key={category} value={category} className="capitalize">
                                {category}
                              </option>
                            ))}
                          </select>

                          <input
                            type="date"
                            value={item.dueDate}
                            onChange={(e) => updateItem(item.id, "dueDate", e.target.value || null)}
                            className="input-base"
                          />

                          <button
                            onClick={() => deleteItem(item.id)}
                            className="inline-flex items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white px-3 py-2 text-sm font-medium text-slate-500 transition-colors hover:border-red-200 hover:text-brand-red"
                          >
                            <Trash2 className="h-4 w-4" />
                            Remove
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function ChecklistSummaryCard({
  label,
  value,
  hint,
}: {
  label: string;
  value: string;
  hint: string;
}) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
      <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-500">{label}</p>
      <p className="mt-2 text-lg font-semibold text-slate-900">{value}</p>
      <p className="mt-1 text-xs text-slate-500">{hint}</p>
    </div>
  );
}
